### PR TITLE
Explain that KO_CONFIG_PATH should be a directory

### PR DESCRIPTION
**Pull request by halvards**
Related: #909

### CODE REVIEW

**Comment by imjasonh** [comment]
https://github.com/ko-build/ko/pull/731 changed `KO_CONFIG_PATH` to allow specifying the file. Is there a bug in that logic?

**Comment by halvards** [comment]
It appears so. Repro steps:

```sh
$ ko version
0.12.0

$ git clone https://github.com/bluebrown/ko-bug-nested-config.git
$ cd ko-bug-nested-config
$ git checkout a07be3e7471a7cc2931cb45d2b52000d52a6557c
$ sed -i 's/dir:.*$/dir: ./' nested/.ko.yaml

$ export KO_CONFIG_PATH="$PWD/nested/.ko.yaml"
$ docker run --rm "$(ko build -L -B ./cmd/app/)"
tag is not used

$ export KO_CONFIG_PATH="$PWD/nested"
$ docker run --rm "$(ko build -L -B ./cmd/app/)"
tag is used
```

**Comment by developer-guy** [comment]
> #731 changed `KO_CONFIG_PATH` to allow specifying the file. Is there a bug in that logic?

Yep, there is a bug related to that because it does not consider the file you supply in the `KO_CONFIG_PATH` because of the viper logic you provide as `v.AddConfigPath(override)`; if the value of the `override` variable is a file, it doesn't consider using the content of it while running  `v.ReadInConfig().` I've faced the same issue while working on #904 ☝️

**Comment by imjasonh** [comment]
I believe handling of `KO_CONFIG_PATH` pointing to a file is handled correctly now, so I'm closing this. If folks would like to improve docs or find bugs please feel free to comment here.

**Pull request closed without merging**
