### PR TITLE
fix: update github.com/awslabs/amazon-ecr-credential-helper to latest version

### PR DESCRIPTION
**Pull request by nesty92**
Resolves: https://github.com/ko-build/ko/issues/1245

And allow the use of OIDC

This is basically:

```
# git checkout main
# go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login
# go mod tidy
# go mod vendor
# git add -A
```

Replacement of: https://github.com/ko-build/ko/pull/1248

### CODE REVIEW

**Review by imjasonh — APPROVED** [review]

**Comment by renanqts** [comment]
Thanks for that.
Could you please release a version with that fix?

**Comment by nesty92** [comment]
@renanqts If you are using the latest container images they are updated

**Comment by renanqts** [comment]
yes, I'm using the binaries. It would be nice to have it there, otherwise, I will use the image

**Comment by cpanato** [comment]
will review and see if there are other things to be released as well

**Comment by renanqts** [comment]
> will review and see if there are other things to be released as well

thanks a lot

**Pull request merged**
