### PR TITLE
Update awslabs/amazon-ecr-credential-helper to latest

### PR DESCRIPTION
**Pull request by emsearcy**
This update fixes an apparent conflict between the amazon-ecr-credential-helper library and the aws-sdk-go-v2 library, introduced when aws-sdk-go-v2 was updated as a byproduct of a cosign upgrade in #1191.

This mismatch resulted in an error: `ecr: Failed to get authorization token: not found, ResolveEndpointV2`

However, this error was not readily apparent due to overridding the ecr-login module's logger to io.Discard in `pkg/commands/config.go`.

Resolves: #1245

### CODE REVIEW

**Comment by mrmahi2003** [comment]
some work is still required in order to merge this pr before reviewing

**Review by cpanato — APPROVED** [review]
lgtm

**Comment by nesty92** [comment]
Please merge this we are unable to use OIDC until the underline ecr-login is updated. This is the error
image

And after the ecr-login is updated everything works

image

**Comment by nesty92** [comment]
Since #1267 was merged this one can be close

**Pull request closed without merging**
